WALL: Create Radio Component
wallace-developments/wallace-frontend pull request #10
Opened 2024-09-11 06:48 UTC by VasudevaVellanki4

## Summary

_Please provide a brief summary of the changes and why they were necessary. Highlight the issue fixed and the context behind the change._

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (code change that neither fixes a bug nor adds a feature)

### Linked Issues

- _Reference any related issues here by linking to JIRA or GitHub Issues._

## JIRA Issue(s)

- [JIRA Issue Link](https://wallaceproject.atlassian.net/browse/WALL-12)

## Checklist (check all)

- [ ] Automated tests have been added, or an explanation for why not
- [ ] Security implications and dependencies on linked features have been considered and explained
- _Provide an explanation if tests were not added. Convince the reviewers._

## Screenshots & Evidence

![image](https://github.com/user-attachments/assets/24133f64-314e-42e2-8739-56a53a78f2c4)

_Include any relevant screenshots, Videos, or links to documentation that provide additional context or proof of functionality._

2024-09-11 07:22 UTC, raj-upadhyayy requested changes
Minor change, rest looks good!

2024-09-11 07:22 UTC, raj-upadhyayy commented on src/components/atoms/RadioComp/RadioComp.tsx
> +    };
can we try, same for dotcolor too
```
const getBorderColor = () => {
  const greenBorder = 'border-green-500';
  const darkGreenBorder = 'border-[#103c34]';

  if (combinedVariant) {
    return combinedVariant === 'combined-green-border' ? greenBorder : darkGreenBorder;
  }

  return variant === 'green-border' ? greenBorder : darkGreenBorder;
};
```

2024-09-12 00:45 UTC, raj-edition commented
Add summary and update PR title please 
<img width="769" alt="Screenshot 2024-09-12 at 6 14 55 AM" src="https://github.com/user-attachments/assets/d4107147-26c3-42f3-a470-adca9ba336e0">

2024-09-12 11:45 UTC, raj-edition requested changes
one small change

2024-09-12 11:45 UTC, raj-edition commented on src/components/atoms/RadioComp/RadioComp.tsx
> +      'peer h-4 w-4 shrink-0 rounded-full border ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed
lets move this outside RadioComp function

2024-09-13 05:33 UTC, raj-edition approved these changes

2024-09-15 16:05 UTC, manikangkan reviewed
We'll have to revisit this, @VasudevaVellanki4 . I think we can make this better.

CC: @raj-edition

2024-09-16 19:20 UTC, manikangkan commented
Merged in https://github.com/wallace-developments/wallace-frontend/pull/30

2024-09-16 19:20 UTC, closed without merging