WALL-23: Create Link Atom Component
wallace-developments/wallace-frontend pull request #11
Opened 2024-09-11 09:32 UTC by VasudevaVellanki4

## Summary

_Please provide a brief summary of the changes and why they were necessary. Highlight the issue fixed and the context behind the change._

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (code change that neither fixes a bug nor adds a feature)

### Linked Issues

- _Reference any related issues here by linking to JIRA or GitHub Issues._

## JIRA Issue(s)

- [JIRA Issue Link](https://wallaceproject.atlassian.net/browse/WALL-23)

## Checklist (check all)

- [ ] Automated tests have been added, or an explanation for why not
- [ ] Security implications and dependencies on linked features have been considered and explained
- _Provide an explanation if tests were not added. Convince the reviewers._

## Screenshots & Evidence
![image](https://github.com/user-attachments/assets/a3f75f00-2b6f-4819-8432-cf1cf748fd77)

_Include any relevant screenshots, Videos, or links to documentation that provide additional context or proof of functionality._

2024-09-11 11:30 UTC, raj-upadhyayy requested changes
Some comments

2024-09-11 11:30 UTC, raj-upadhyayy commented on src/components/atoms/LinkAtom/LinkAtom.tsx
> +    <a
Instead of anchor tag we need to use the next js link tag https://nextjs.org/docs/pages/api-reference/components/link

2024-09-11 11:30 UTC, raj-upadhyayy commented on src/components/atoms/LinkAtom/LinkAtom.tsx
> +              }}
styles would be updated once link tag is used

2024-09-12 11:44 UTC, raj-edition requested changes
some changes

2024-09-12 11:44 UTC, raj-edition commented on src/components/atoms/LinkAtom/LinkAtom.tsx
> +  );
use the https://nextjs.org/docs/pages/api-reference/components/link component instead of <a> please

2024-09-13 05:35 UTC, raj-edition approved these changes

2024-09-15 16:16 UTC, manikangkan commented on src/components/atoms/CustomLink/CustomLink.tsx
> +
Let's add jsdocs

2024-09-15 16:17 UTC, manikangkan commented on src/components/atoms/CustomLink/CustomLink.tsx
> +        <span>↗</span>
Since we've configured the `SVGIcon` comp and Icon Sprit, let's get the icon and configure here

2024-09-15 16:18 UTC, manikangkan commented on src/components/atoms/CustomLink/CustomLink.tsx
> +}
we don't need this

2024-09-16 19:20 UTC, closed without merging