WALL-33: Create PropertyCard comp
wallace-developments/wallace-frontend pull request #26
Opened 2024-09-13 17:53 UTC by manikangkan

## Summary

Create PropertyCard comp

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (code change that neither fixes a bug nor adds a feature)

### Linked Issues

Null

## JIRA Issue(s)

- [JIRA Issue Link](https://wallaceproject.atlassian.net/browse/WALL-32)

## Checklist (check all)

- [ ] Automated tests have been added, or an explanation for why not
- [ ] Security implications and dependencies on linked features have been considered and explained
- _Provide an explanation if tests were not added. Convince the reviewers._

## Screenshots & Evidence
<img width="1453" alt="image" src="https://github.com/user-attachments/assets/9576807c-a949-49b8-aa8c-303af9b4327c">
<img width="1453" alt="image" src="https://github.com/user-attachments/assets/d9bd0db0-1bfc-4d3a-8c34-7c0885219532">

2024-09-16 02:40 UTC, raj-edition reviewed
One change Mani

2024-09-16 02:40 UTC, raj-edition commented on src/modules/PropertyCard/PropertyCard.tsx
> +          {amenities.length > 0 && (
lets create a common utility function for arrays that check if the array is empty or not. Lets use that at all places moving forward

2024-09-16 02:42 UTC, raj-edition requested changes

2024-09-16 02:42 UTC, raj-edition commented on src/modules/PropertyCard/PropertyCard.tsx
> +          )}
update to use https://github.com/wallace-developments/wallace-frontend/pull/21

2024-09-16 11:09 UTC, VasudevaVellanki4 approved these changes

2024-09-16 11:21 UTC, manikangkan commented on src/modules/PropertyCard/PropertyCard.tsx
> +          {amenities.length > 0 && (
Sorted

2024-09-16 11:21 UTC, manikangkan commented on src/modules/PropertyCard/PropertyCard.tsx
> +          )}
Sorted

2024-09-16 13:49 UTC, VasudevaVellanki4 approved these changes

2024-09-17 06:09 UTC, raj-edition approved these changes

2024-09-17 06:09 UTC, merged